#!/usr/bin/env bash
#
#
VERSION="1.0.1"
#cp -f nexus-utilities/nexus-utilities.version /usr/local/src/nexus/
cp -f nexus-utilities/*.conf /usr/local/src/nexus/
cp -f nexus-utilities/*.html /usr/local/share/nexus
cp -f nexus-utilities/*.jpg $HOME/Pictures/
cp -f nexus-utilities/*.example $HOME/
sudo cp -f nexus-utilities/*.sh /usr/local/bin/
sudo cp -f nexus-utilities/*.py /usr/local/bin/
sudo cp -f nexus-utilities/*.desktop /usr/local/share/applications/
sudo cp -f nexus-utilities/*.template /usr/local/share/applications/
